### ISSUE TITLE
Shift and click with brush draws a line (good) but doesn't show line preview (not so good)

### ISSUE THREAD

**Issue by therealrobster** [LibreSprite/LibreSprite-proposals#46] opened 2021-12-02 22:45 UTC
As the subject suggests, when clicking once to set your origin point, then pressing and holding shift, the preview of your line should show until you click again on the destination point.  That way you can see if your line is 'in the right place' before committing. 

I hope that helps

**Comment by Zughy** [comment] 2021-12-03 18:57
Duplicate of #10 (really needed feature)

**Closed as completed by Zughy** 2021-12-03 18:57 UTC
Labels: feature proposal
